server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  location = /runtime-config.js {
    add_header Cache-Control 'no-store, no-cache, must-revalidate';
    try_files $uri =404;
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control 'public, immutable';
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
